name: Deploy to Fly
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.2.65
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}