name: Preview App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    permissions: write-all
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}
    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}
    outputs:
      URL: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        id: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          org: ${{ vars.FLY_ORG }}
          region: ${{ vars.FLY_REGION }}
          name: pr-${{ github.event.number }}-${{ github.event.repository.name }}
      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v2
        if: ${{ github.event.action == 'closed' }}
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pr-${{ github.event.number }}

  comment:
    if: ${{ github.event.created == false }}
    runs-on: ubuntu-latest
    needs: [ deploy_app ]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Comment url on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed to ${{ needs.deploy_app.outputs.URL }} 🚀'
            })